AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  jle-sam-test

  Sample SAM Template for jle-sam-test

Globals:
  Function:
    Runtime: java11
Resources:
  SimpleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.SimpleApp::handleRequest
  DynamoDbFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.DynamoDbApp::handleRequest
      MemorySize: 256
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FeelingsTable
        - DynamoDBWritePolicy:
            TableName: !Ref FeelingsTable
  AthenaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.AthenaApp::handleRequest
      MemorySize: 256
      Timeout: 10
      Policies:
        - AthenaQueryPolicy:
            WorkGroupName: "primary"
  FeelingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: feelings_table
      AttributeDefinitions:
        - AttributeName: feelingId
          AttributeType: S
      KeySchema:
        - AttributeName: feelingId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
